/// \file
/// \brief The parser for the assembly syntax
///
/// TODO: keep comments and such stuff attached
///       (to put data, generated by compiler there)
///

#ifndef IVM_ASM_PARSER_AST
#define IVM_ASM_PARSER_AST

#include "ivm/common/parser/span.h"
#include "ivm/common/array.h"

/// Type of the node
typedef enum {

  /// Instruction, like `push 42`
  AST_INSTR,

  /// Label, like `foobar:`
  AST_LABEL,

  /// Constant directive, like `.const SOMETHING 0xff`
  AST_DIR_CONST,

  /// String/base64 directive, like `.ascii "Hello world\n\0"`
  /// Includes also fall under this
  AST_DIR_BLOB,

  /// Number directive, like `.u32 0xff00ff00`
  AST_DIR_NUMBER,

  /// Symbol type, like `.func`
  AST_DIR_SYMTYPE

} ast_node_type;

/// One "node" of ast
typedef struct {

  ast_node_type type;

  union {

    /// AST_INSTR
    struct {
      ivm_span name;
      ia_arr$(ivm_span) args;
      size_t pc;
    } as_instr;

    /// AST_LABEL
    struct {
      ivm_span name;
    } as_label;

    /// AST_DIR_CONST
    struct {
      ivm_span dir_name;
      ivm_span name;
      ivm_span expression;
    } as_dir_const;

    /// AST_DIR_BLOB
    struct {
      ivm_span dir_name;
      ivm_span value;
    } as_dir_blob;

    /// AST_DIR_NUMBER
    struct {
      ivm_span dir_name;
      ivm_span number_expr;
    } as_dir_number;

    // AST_DIR_SYMTYPE
    struct {
      ivm_span dir_name;
    } as_dir_symtype;
  };
} ast_node;


/// Parse given file into list of AST nodes
ia_arr$(ast_node) iasm_parse_file(ivm_file* file);

void iasm_dump_ast(ia_arr$(ast_node) ast);

#endif
