"""
Generates outline data from black-and-white video

Uses cv2. 
"""

import cv2

VIDEO_PATH = './bad_apple.mp4'
OUTPUT_PATH = './video.gen.s'
FRAME_CAP = -1

def vectorize_image(img, epsilon=1.0, min_contour_area=10):
    """
    Convert a black-and-white image to polylines.
    
    Args:
        image_path: Path to the image file
        epsilon: Simplification factor (higher = more simplified)
        min_contour_area: Minimum contour area to keep (remove noise)
    
    Returns:
        List of polylines, each polyline is a list of (x, y) points

    This function was generated by DeepSeek, because I don't remember
    that from last time I used it.

    """
    # Load image as grayscale
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Convert to binary (black and white)
    # Assumes white objects on black background
    _, binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
    
    # Find contours (the outlines)
    contours, hierarchy = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    
    polylines = []
    
    for contour in contours:
        # Filter out tiny noise contours
        if cv2.contourArea(contour) < min_contour_area:
            continue
        
        # Simplify the contour by removing redundant points
        perimeter = cv2.arcLength(contour, True)
        simplified = cv2.approxPolyDP(contour, epsilon, True)

        # Convert from (N,1,2) to list of (x,y) points
        points = simplified.reshape(-1, 2).tolist()
        
        # For closed contours, add the first point at the end to close the loop
        if len(points) > 1:
            points.append(points[0])
            polylines.append(points)
    
    return polylines


def main():
    out = open(OUTPUT_PATH, "w")
    out.write(f"// GENERATED FILE, DO NOT EDIT\n")
    out.write(f"// This is a sequence of commands for each frame, for CRT to render the video\n")
    out.write(f"// It was generated by outlines.py, from {VIDEO_PATH}\n")
    out.write(f"\n")
    out.write(f"jmp main\n")

    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        raise ValueError(f"Failed to open video")
    frameno = 0
    while True:
        print(f"Frame {frameno}\r", end='')
        have_frame, frame = cap.read()
        if not have_frame or (FRAME_CAP != -1 and frameno > FRAME_CAP):
            break
        outlines = vectorize_image(frame)

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        h, w = frame.shape[:2]

        out.write(f"_outlines_frame_{frameno}:\n")
        for poly in outlines:
            for i, pt in enumerate(poly):
                x, y = pt[0], pt[1]
                x = int(x / w * 0xffff).to_bytes(2, 'little')
                y = int(y / w * 0xffff).to_bytes(2, 'little') # keep aspect

                typ = b'\x01' if i == 0 else b'\x02'
                cmd = (typ + b'\x00\x00\x00' + y + x).hex()
                hex = [ "\\x" + cmd[2*i:2*i+2] for i in range(8) ]
                out.write(f"    .ascii \"{''.join(hex)}\"\n")
        out.write(f"    .ascii \"\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\"\n")
        out.write(f"\n")

        frameno += 1

    out.write(f"outlines_frametable:\n")
    for i in range(frameno):
        out.write(f"    .i64 _outlines_frame_{i}\n")
    out.write(f".const outlines_framecount {frameno}\n")
    print()
if __name__ == "__main__":
    main()
